name: Release Canary Version

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: |
          npm install
      - name: Build project
        run: |
          BETA=true npm run release
        env:
          GITHUB_BRANCH: ${{ github.ref }}
      - name: Create Release
        id: create_release
        uses: webclipper/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          replace_old_tag: true
          tag_name: canary
          body: 'Be warned: Canary can be unstable.'
          release_name: Release Canary Version
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: webclipper/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          release_id: ${{ steps.create_release.outputs.id }}
          asset_path: ./release/web_clipper_chrome_canary.zip
          asset_name: web_clipper_chrome_canary.zip
          asset_content_type: application/zip
      - name: Upload Firefox Release Asset
        id: upload-firefox-release-asset
        uses: webclipper/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          release_id: ${{ steps.create_release.outputs.id }}
          asset_path: ./release/web_clipper_firefox_canary.zip
          asset_name: web_clipper_firefox_canary.zip
          asset_content_type: application/zip
